apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: wussh
  labels:
    account: order-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: wussh
  labels:
    app: order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: v1
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      serviceAccountName: order-service
      containers:
      - name: order-service
        image: ghcr.io/wussh/a433-microservices:order-service
        ports:
        - containerPort: 3000
        env: 
          - name: PORT
            value: "3000"
          - name: AMQP_URL
            value: "amqp://rabbitmq:5672"
            
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: wussh
  labels:
    app: order-service
    service: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 3000
    name: http
  type: NodePort