apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipping-service
  namespace: wussh
  labels:
    account: shipping-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: wussh
  labels:
    app: shipping-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
      version: v1
  template:
    metadata:
      labels:
        app: shipping-service
        version: v1
    spec:
      serviceAccountName: shipping-service
      containers:
      - name: shipping-service
        image: ghcr.io/wussh/a433-microservices:shipping-service
        ports:
        - containerPort: 3001
        env: 
          - name: PORT
            value: "3001"
          - name: AMQP_URL
            value: "amqp://rabbitmq:5672"
---

apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: wussh
spec:
  selector:
    app: shipping-service
  ports:
  - port: 3001
  type: NodePort